# yaml-language-server: $schema=https://raw.githubusercontent.com/amnweb/yasb/main/schema.json

# Author: Nishu
# For more information, visit https://github.com/amnweb/yasb/wiki

watch_stylesheet: true
watch_config: true
debug: false
update_check: false

bars:
  primary-bar:
    enabled: true
    screens:
      - "*"
    class_name: yasb-bar
    alignment:
      position: top
      align: center
    window_flags:
      always_on_top: false
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: 100%
      height: 34
    widgets:
      left: []
      center:
        - clock
      right:
        - power_menu

widgets:
  clock:
    type: yasb.clock.ClockWidget
    options:
      #label: '{%H:%M}<span>{alarm}</span>'
      label: " <span>{alarm}</span> {%a, %d %b %H:%M}"
      label_alt: " <span>{alarm}</span> {%I:%M:%S %p}"
      alarm_icons:
        enabled: "\uf0f3"
        disabled: "\uf0a2"
        snooze: "\uf1f6"
      calendar:
        blur: true
        round_corners: true
        alignment: center
        # direction: down
        extended: false
        show_years: true
        show_holidays: true
        show_week_numbers: true
      callbacks:
        on_left: toggle_calendar
        on_middle: toggle_label
        #on_right: "context_menu"
        on_right: "exec cmd.exe /c start ms-clock:"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\u23fb"
      buttons:
        restart: ["\uead2", "Restart"]
        shutdown: ["\uf011", "Shut Down"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        lock: ["\uea75", "Lock"]
        cancel: ["\udb81\udf3a", "Cancel"]
