# yaml-language-server: $schema=https://raw.githubusercontent.com/amnweb/yasb/main/schema.json

# Author: Nishu
# For more information, visit https://github.com/amnweb/yasb/wiki

watch_stylesheet: true
watch_config: true
debug: false
update_check: false

bars:
  primary-bar:
    enabled: true
    screens:
      - "*"
    class_name: yasb-bar
    alignment:
      position: top
      align: center
    window_flags:
      always_on_top: false
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: 100%
      height: 34
    widgets:
      left:
        - home
      center:
        - clock
      right:
        - power_menu

widgets:
  clock:
    type: yasb.clock.ClockWidget
    options:
      #label: '{%H:%M}<span>{alarm}</span>'
      label: " <span>{alarm}</span> {%a, %d %b %H:%M}"
      label_alt: " <span>{alarm}</span> {%I:%M:%S %p}"
      alarm_icons:
        enabled: "\uf0f3"
        disabled: "\uf0a2"
        snooze: "\uf1f6"
      calendar:
        blur: true
        round_corners: true
        alignment: center
        # direction: down
        extended: false
        show_years: true
        show_holidays: true
        show_week_numbers: true
      callbacks:
        on_left: toggle_calendar
        on_middle: toggle_label
        #on_right: "context_menu"
        on_right: "exec cmd.exe /c start ms-clock:"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: true
      show_user: true
      profile_image_size: 120
      blur: true
      blur_background: true
      button_row: 4
      menu_style: "fullscreen"
      buttons:
        lock: ["\uea75", "Lock"]
        signout: ["\udb80\udf43", "Sign out"]
        sleep: ["\u23fe", "Sleep"]
        hibernate: ["\uf28e", "Hibernate"]
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        force_shutdown: ["!\uf011!", "Force Shut Down"]
        force_restart: ["!\uead2!", "Force Restart"]
        cancel: ["\udb81\udf3a", "Cancel"]
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\uf40e</span>"
      menu_list:
        - { title: "User Home", path: "~" }
        - { title: "Download", path: "D:\\Downloads" }
        - { title: "Documents", path: "C:\\Users\\amn\\Documents" }
        - { title: "Pictures", path: "C:\\Users\\amn\\Pictures" }
        - {
            title: "Sound Settings",
            command: "cmd.exe /c start ms-settings:sound",
          }
        - { title: "Windows Settings", uri: "ms-settings:" }
        - { separator: true }
        - { title: "PowerShell", command: "powershell.exe", show_window: true }
        - {
            title: "Winget Update",
            command: "powershell.exe",
            args: ["-NoProfile", "-NoExit", "-Command", "winget upgrade"],
            show_window: true,
          }
        - { title: "Registry Editor", path: "C:\\Windows\\regedit.exe" }
        - { title: "Event Viewer", path: "C:\\Windows\\System32\\eventvwr.msc" }
        - {
            title: "Device Manager",
            path: "C:\\Windows\\System32\\devmgmt.msc",
          }
        - { title: "Services", path: "C:\\Windows\\System32\\services.msc" }
        - {
            title: "Resource Monitor",
            path: "explorer.exe shell:RecycleBinFolder",
          }
        - {
            title: "Add/Remove Programs",
            path: "C:\\Windows\\System32\\appwiz.cpl",
          }
      system_menu: true
      power_menu: true
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "System"
      offset_top: 0
      offset_left: -12
