# yaml-language-server: $schema=https://raw.githubusercontent.com/amnweb/yasb/main/schema.json

# Author: Nishu
# For more information, visit https://github.com/amnweb/yasb/wiki

watch_stylesheet: true
watch_config: true
debug: false
update_check: false

bars:
  primary-bar:
    enabled: true
    screens:
      - "*"
    class_name: yasb-bar
    alignment:
      position: top
      align: center
    window_flags:
      always_on_top: true
      windows_app_bar: true
    dimensions:
      width: 100%
      height: 34
    widgets:
      left: []
      center:
        - clock
      right: []

widgets:
  clock:
    type: yasb.clock.ClockWidget
    options:
      #label: '{%H:%M}<span>{alarm}</span>'
      label: "{%a, %d %b %H:%M}"
      label_alt: "{%I:%M:%S %p}"
      callbacks:
        on_left: toggle_calendar
        on_middle: toggle_label
        #on_right: "context_menu"
        on_right: "exec cmd.exe /c start ms-clock:"
